// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mnemo.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Mnemo.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MnemoDbContext))]
    [Migration("20251216032340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mnemo.Domain.Entities.ComplianceCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<Guid?>("CheckedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_by_user_id");

                    b.Property<decimal?>("ComplianceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("compliance_score");

                    b.Property<Guid>("ContractRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_requirement_id");

                    b.Property<string>("Gaps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("gaps");

                    b.Property<bool?>("IsCompliant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_compliant");

                    b.Property<string>("PolicyIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("policy_ids");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_compliance_checks");

                    b.HasIndex("CheckedByUserId")
                        .HasDatabaseName("i_x_compliance_checks_checked_by_user_id");

                    b.HasIndex("ContractRequirementId")
                        .HasDatabaseName("i_x_compliance_checks_contract_requirement_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_compliance_checks_tenant_id");

                    b.ToTable("compliance_checks");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.ContractRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("AdditionalInsuredRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("additional_insured_required");

                    b.Property<decimal?>("AutoCombinedSingleMin")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("auto_combined_single_min");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullRequirements")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("full_requirements");

                    b.Property<decimal?>("GlAggregateMin")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("gl_aggregate_min");

                    b.Property<decimal?>("GlEachOccurrenceMin")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("gl_each_occurrence_min");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool?>("PrimaryNoncontributoryRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("primary_noncontributory_required");

                    b.Property<decimal?>("ProfessionalLiabilityMin")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("professional_liability_min");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UmbrellaMin")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("umbrella_min");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("WaiverOfSubrogationRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("waiver_of_subrogation_required");

                    b.Property<bool?>("WcRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("wc_required");

                    b.HasKey("Id")
                        .HasName("p_k_contract_requirements");

                    b.HasIndex("SourceDocumentId")
                        .HasDatabaseName("i_x_contract_requirements_source_document_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_contract_requirements_tenant_id");

                    b.ToTable("contract_requirements");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_ids");

                    b.Property<string>("PolicyIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("policy_ids");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_conversations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_conversations_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_conversations_user_id");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Coverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AggregateLimit")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("aggregate_limit");

                    b.Property<string>("CoverageSubtype")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("coverage_subtype");

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("coverage_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Deductible")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("deductible");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<decimal?>("EachOccurrenceLimit")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("each_occurrence_limit");

                    b.Property<decimal?>("ExtractionConfidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("extraction_confidence");

                    b.Property<bool?>("IsClaimsMade")
                        .HasColumnType("boolean")
                        .HasColumnName("is_claims_made");

                    b.Property<bool?>("IsOccurrenceForm")
                        .HasColumnType("boolean")
                        .HasColumnName("is_occurrence_form");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<decimal?>("Premium")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("premium");

                    b.Property<DateOnly?>("RetroactiveDate")
                        .HasColumnType("date")
                        .HasColumnName("retroactive_date");

                    b.HasKey("Id")
                        .HasName("p_k_coverages");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("i_x_coverages_policy_id");

                    b.HasIndex("PolicyId", "CoverageType");

                    b.ToTable("coverages");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text")
                        .HasColumnName("processing_error");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("processing_status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<Guid?>("SubmissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_group_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("p_k_documents");

                    b.HasIndex("SubmissionGroupId")
                        .HasFilter("submission_group_id IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_documents_tenant_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("i_x_documents_uploaded_by_user_id");

                    b.HasIndex("TenantId", "ProcessingStatus");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int?>("PageEnd")
                        .HasColumnType("integer")
                        .HasColumnName("page_end");

                    b.Property<int?>("PageStart")
                        .HasColumnType("integer")
                        .HasColumnName("page_start");

                    b.Property<string>("SectionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section_type");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id")
                        .HasName("p_k_document_chunks");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("i_x_document_chunks_document_id");

                    b.ToTable("document_chunks");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.IndustryBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IndustryClass")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("industry_class");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NaicsCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("naics_code");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RecommendedCoverages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommended_coverages");

                    b.Property<string>("SicCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sic_code");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_industry_benchmarks");

                    b.HasIndex("IndustryClass");

                    b.ToTable("industry_benchmarks");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CitedChunkIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cited_chunk_ids");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("p_k_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("i_x_messages_conversation_id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CarrierNaic")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("carrier_naic");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("carrier_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<decimal?>("ExtractionConfidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("extraction_confidence");

                    b.Property<string>("InsuredAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("insured_address_line1");

                    b.Property<string>("InsuredAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("insured_address_line2");

                    b.Property<string>("InsuredCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("insured_city");

                    b.Property<string>("InsuredName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("insured_name");

                    b.Property<string>("InsuredState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("insured_state");

                    b.Property<string>("InsuredZip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("insured_zip");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("policy_number");

                    b.Property<string>("PolicyStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("policy_status");

                    b.Property<DateOnly?>("QuoteExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("quote_expiration_date");

                    b.Property<string>("QuoteNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("quote_number");

                    b.Property<string>("RawExtraction")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_extraction");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<Guid?>("SubmissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_group_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("TotalPremium")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_premium");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_policies");

                    b.HasIndex("SourceDocumentId")
                        .HasDatabaseName("i_x_policies_source_document_id");

                    b.HasIndex("SubmissionGroupId")
                        .HasFilter("submission_group_id IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_policies_tenant_id");

                    b.HasIndex("TenantId", "InsuredName");

                    b.HasIndex("TenantId", "PolicyStatus");

                    b.ToTable("policies");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("p_k_tenants");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("SupabaseUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("supabase_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_users_tenant_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Webhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("events");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Secret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("secret");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("p_k_webhooks");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_webhooks_tenant_id");

                    b.ToTable("webhooks");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("WebhookId")
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_id");

                    b.HasKey("Id")
                        .HasName("p_k_webhook_deliveries");

                    b.HasIndex("WebhookId")
                        .HasDatabaseName("i_x_webhook_deliveries_webhook_id");

                    b.ToTable("webhook_deliveries");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.ComplianceCheck", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.User", "CheckedByUser")
                        .WithMany("ComplianceChecks")
                        .HasForeignKey("CheckedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_compliance_checks__users_checked_by_user_id");

                    b.HasOne("Mnemo.Domain.Entities.ContractRequirement", "ContractRequirement")
                        .WithMany("ComplianceChecks")
                        .HasForeignKey("ContractRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_compliance_checks__contract_requirements_contract_requirement~");

                    b.HasOne("Mnemo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ComplianceChecks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_compliance_checks__tenants_tenant_id");

                    b.Navigation("CheckedByUser");

                    b.Navigation("ContractRequirement");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.ContractRequirement", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Document", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_contract_requirements__documents_source_document_id");

                    b.HasOne("Mnemo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ContractRequirements")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_contract_requirements__tenants_tenant_id");

                    b.Navigation("SourceDocument");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Conversations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_conversations__tenants_tenant_id");

                    b.HasOne("Mnemo.Domain.Entities.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_conversations__users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Coverage", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Policy", "Policy")
                        .WithMany("Coverages")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_coverages__policies_policy_id");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Document", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Documents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_documents__tenants_tenant_id");

                    b.HasOne("Mnemo.Domain.Entities.User", "UploadedByUser")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_documents__users_uploaded_by_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_document_chunks_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Message", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_messages_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Policy", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Document", "SourceDocument")
                        .WithMany("Policies")
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_policies_documents_source_document_id");

                    b.HasOne("Mnemo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Policies")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_policies__tenants_tenant_id");

                    b.Navigation("SourceDocument");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.User", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Webhook", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Webhooks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_webhooks_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("Mnemo.Domain.Entities.Webhook", "Webhook")
                        .WithMany("Deliveries")
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_webhook_deliveries_webhooks_webhook_id");

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.ContractRequirement", b =>
                {
                    b.Navigation("ComplianceChecks");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Policy", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("ComplianceChecks");

                    b.Navigation("ContractRequirements");

                    b.Navigation("Conversations");

                    b.Navigation("Documents");

                    b.Navigation("Policies");

                    b.Navigation("Users");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.User", b =>
                {
                    b.Navigation("ComplianceChecks");

                    b.Navigation("Conversations");

                    b.Navigation("UploadedDocuments");
                });

            modelBuilder.Entity("Mnemo.Domain.Entities.Webhook", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
